### ISSUE TITLE
model : 논문 읽기 및 모델 구현

### ISSUE THREAD

**Issue by hyunjjjin** [kookmin-sw/capstone-2023-15#10]
구현한 모델 실험 및 fine tuning

**Comment by Ahnho** [comment]
Latent Space Autoregression for Novelty Detection 논문 읽기

**Comment by Ahnho** [comment]
OCGAN: One-class Novelty Detection Using GANs with Constrained Latent Representations 논문 읽기

**Comment by Ahnho** [comment]
CSI 논문 리뷰 및 코드분석

**Comment by Ahnho** [comment]
다른 데이터관해서 학습을 돌려 결과를 본 후 이 모델을 계속 사용을 할건지 다른 모델을 사용할건지 결정

**Comment by Ahnho** [comment]
최종적으로 CSI 모델을 사용하기로 함
