### ISSUE TITLE
데이터 마이닝을 통해 얻은 데이터 모드 문제

### ISSUE THREAD

**Issue by Ahnho** [kookmin-sw/capstone-2023-15#36]

**Comment by Ahnho** [comment]
데이터 마이닝을 통해 들고온 이미지 모드가 P로 설정 되어 있어 RGB로 바꿔야함

**Comment by ChanHHOO** [comment]
혹시 조금 자세히 설명해주실 수 있나요 ? 모든 이미지가 그런 상태일까요 ?

**Comment by hyunjjjin** [comment]
P모드가 어떤 모드인지 알 수 있을까요?

**Comment by Ahnho** [comment]
P (Palette )  이미지에 사용되는 색상을 제한하는 작은 색상 집합 ,  파일 크기를 줄어듬
데이터 마이닝을 하였을때의 대부분의 이미지가 mode:P 로 되어있음(에러 발생), 
이러한 이유로 데이터 마이닝 과정중에서 mode:P를  image mode: RGB로 바꾸는것이 좋아보입니다.
모델에서도 바꿀수 있긴합니다.
