### ISSUE TITLE
data preprocessing : 데이터 전처리 코드 작성

### ISSUE THREAD

**Issue by hyunjjjin** [kookmin-sw/capstone-2023-15#9]
python - pytorch 활용하여 크롤링한 데이터 전처리 일반화

**Comment by Ahnho** [comment]
python을 활용하여 작가의 데이터를 받아와 자동적으로 저장할 파일생성과 unzip code작성

**Comment by Ahnho** [comment]
직접만든 custom data를 라벨링, 전처리 해주는 code 작성

**Comment by Ahnho** [comment]
CSI  model을 사용시 shift transformation을 작가의 데이터에 맞게 설정을 해주어야한다.
